import Foundation
import SwiftUI

struct PrivacyPage: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                Text("Privacy Policy")
                    .font(.title)
                    .fontWeight(.bold)
                    .padding(.bottom, 10)
                
                Text("Majestic AV LLC (\"we,\" \"our,\" or \"us\") is committed to protecting your privacy. We never collect, share or store any personal information or messages. All messages and images generated by the Que Cat app (\"the App\") are fully owned by and represent you, the user. Any personal information entered into the App is exclusively stored locally or sent encrypted directly to the OpenAI API. The only third parties involved with the App are OpenAI and Apple. The information shared with them is limited to what is explicitly required to utilize their services and is outlined in their respective privacy policies.")
                    .font(.body)
                
                Text("Legal Policy")
                    .font(.title)
                    .fontWeight(.bold)
                    .padding(.bottom, 10)
                    .padding(.top, 20)
                
                Text("The App is intended for entertainment or experimentation purposes only. Majestic AV is not responsible for any outcomes or results, and we do not intend to cause any harm. By using the App, you acknowledge and agree that you assume all risk and liability associated with the use of the App. We shall not be held responsible for any misuse of the App, and we make no representations or warranties of any kind, whether express or implied, with respect to the App, including but not limited to its accuracy, reliability, suitability, or availability.")
                    .font(.body)

                VStack(alignment: .center, spacing: 10) {
                    Spacer()
                    Button(action: {
                        UIApplication.shared.open(URL(string: "https://openai.com/privacy/")!)
                    }) {
                        Text("OpenAI Privacy Policy")
                            .font(.caption)
                            .underline()
                    }
                    Spacer()
                }
                .padding(.top, 20)
            }
            .padding(.horizontal, 20)
            .padding(.vertical, 30)
        }
    }
}
